exec-once = uwsm-app -- xdg-terminal-exec -e opencode
exec-once = uwsm-app -- xdg-terminal-exec -e cmatrix
# exec-once = joshuto  # TUI app: needs a terminal wrapper to launch correctly
#   use instead: exec-once = uwsm-app -- xdg-terminal-exec -e joshuto
exec-once = ~/.config/hypr/scripts/audio-auto-default.sh

exec-once = sleep 2 && hyprctl dispatch workspace 1
