# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#061a1c"

# Main text color
theme[main_fg]="#a0f0e8"

# Title color for boxes
theme[title]="#a0f0e8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#26FFDF"

# Background color of selected item in processes box
theme[selected_bg]="#061a1c"

# Foreground color of selected item in processes box
theme[selected_fg]="#26FFDF"

# Color of inactive/disabled text
theme[inactive_fg]="#061a1c"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#a0f0e8"

# Background color of the percentage meters
theme[meter_bg]="#061a1c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a0f0e8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#cc66ff"
theme[mem_box]="#26ff88"
theme[net_box]="#ff4466"
theme[proc_box]="#26FFDF"

# Box divider line and small boxes line color
theme[div_line]="#061a1c"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#26ff88"
theme[temp_mid]="#ccff66"
theme[temp_end]="#ff4466"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#26FFDF"
theme[cpu_mid]="#4488ff"
theme[cpu_end]="#cc66ff"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#cc66ff"
theme[free_mid]="#4488ff"
theme[free_end]="#26FFDF"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#4488ff"
theme[cached_mid]="#26FFDF"
theme[cached_end]="#cc66ff"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#ccff66"
theme[available_mid]="#ff4466"
theme[available_end]="#ff4466"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#26ff88"
theme[used_mid]="#26FFDF"
theme[used_end]="#4488ff"

# Download graph colors (Peach -> Red)
theme[download_start]="#ccff66"
theme[download_mid]="#ff4466"
theme[download_end]="#ff4466"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#26ff88"
theme[upload_mid]="#26FFDF"
theme[upload_end]="#4488ff"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#26FFDF"
theme[process_mid]="#4488ff"
theme[process_end]="#cc66ff"
