background = #061a1c
foreground = #a0f0e8
cursor-color = #26FFDF
selection-background = #094248
selection-foreground = #a0f0e8

palette = 0=#031011
palette = 1=#ff4466
palette = 2=#26ff88
palette = 3=#ccff66
palette = 4=#4488ff
palette = 5=#cc66ff
palette = 6=#26FFDF
palette = 7=#c4f5ef
palette = 8=#061a1c
palette = 9=#ff7799
palette = 10=#66ffaa
palette = 11=#ddff99
palette = 12=#77aaff
palette = 13=#dd99ff
palette = 14=#66ffe8
palette = 15=#e0faf6
