foreground #a0f0e8
background #061a1c
selection_foreground #a0f0e8
selection_background #094248

cursor #26FFDF
cursor_text_color #061a1c

active_border_color #26FFDF
active_tab_background #26FFDF

color0 #031011
color1 #ff4466
color2 #26ff88
color3 #ccff66
color4 #4488ff
color5 #cc66ff
color6 #26FFDF
color7 #c4f5ef
color8 #061a1c
color9 #ff7799
color10 #66ffaa
color11 #ddff99
color12 #77aaff
color13 #dd99ff
color14 #66ffe8
color15 #e0faf6
